version: "3"
services:
  postgres:
    image: postgres
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DATABASE: gorm
  server:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
