GET http://localhost:8080/posts

###

GET http://localhost:8080/posts/2

###
POST  http://localhost:8080/posts
Content-Type: application/json

{
    "title": "test",
    "author": "max",
    "description": "test",
    "imagesrc": "none"
}


###

POST  http://localhost:8080/posts/1/comments
Content-Type: application/json

{
   "author": "max_2",
   "body" : "hello, comment"
}

###
GET  http://localhost:8080/posts/1/comments

###

PUT  http://localhost:8080/posts/1/comments/1
Content-Type: application/json

{
   "author": "update",
   "body" : "update"
}

###

DELETE  http://localhost:8080/posts/1/comments/2