name: FrontPage CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      APPLICATION_CREDENTIALS:  ${{ secrets.GCP_CREDENTIALS }}
    
    steps:
    - name: checkout src
      uses: actions/checkout@v1
      
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 'v13.x'
    
    - name: Cache Deps
      uses: actions/cache@v1
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - run: npm install
      working-directory: ./frontend
    - run: npm run build
      working-directory: ./frontend
            
    - name: deploy with gcloud
      uses: actions-hub/gcloud@master
      env:
        CLI: gsutil
      with:
        args: rsync -d -R frontend/build gs://max-portfolio8821/imageboard
        
    - name: set Access Control List
      uses: actions-hub/gcloud@master
      env:
        CLI: gsutil
      with:
        args: acl ch -r -u AllUsers:R gs://max-portfolio8821/imageboard
        
